### ISSUE TITLE
Alpha 1.0.4 - "more device info" not populating in text box

### ISSUE THREAD

**Issue by msd-rjoachim** [iamtheyammer/gam-cros-win-wrapper#22] opened 2019-05-06 18:32 UTC
During the initial device information gathering process, "getting more device info" step doesn't populate into the text box.

"Get Info" button no longer populates extra information in the text box either.

**Comment by iamtheyammer** [comment] 2019-05-07 03:55
This was a bug caused by me clearing the text field when stopping loading. Fixed, but I'll wait for the commit to close it.

**Closed** 2019-05-07 04:19 UTC
